#!/bin/bash
#OpenAM Shell Scripts Seetings
#sudo chmod 400 once set!

#URL Protocol of OpenAM Server (HTTP or HTTPS)
PROTOCOL=HTTP


#FQDN
#OPENAM_SERVER=app2.ssobridge.com
OPENAM_SERVER=am1.ssobridge.com
#FQDN; change this to match your OpenAM servers host name
OPENAM_SERVER=app2.ssobridge.com

#Server Port
OPENAM_SERVER_PORT=8080

#Returning data format. (xml or json)
FORMAT=json   

#Protected Resource (URL); Change this to match the resource you are testing
PROTECTED_RESOURCE="http://app2.ssobridge.com/index.html"

#Filter
FILTER="*.ssobridge.com"
